#!/usr/bin/env python
# coding=utf-8
import os
from docopt import docopt
from register import setDatamodel, setUnit, setArticle

if __name__ == '__main__':
    helpdoc = """Tools to use gdc(grabbing datas client) conviently.
    Usage:
      gdc (-h|--help)
      gdc init (-k|--key) <key> (-v|--val) <val>
      gdc register model (-f|--filepath) <filepath>
      gdc register unit (-f|--filepath) <filepath>
      gdc register article (-f|--filepath) <filepath>

    Options:
      -h,  --help        Show help document.
      -f,  --filepath    File path of project.
      -c,  --comment     Comment of unit, means what kind of datas you grab.
      -p,  --pinyin      Pin yin of article's Chinese name, means which src datas are from, for example, rujia-http://www.homeinns.com
      -s,  --src         Source host of datas, for example, www.homeinns.com-http://www.homeinns.com
    """
    params = docopt(helpdoc)
    if params.get('init'):
        pass
        # initConfig()
        # print 'Init config settings successfully.'
        # initModel()
        # print 'Init data models successfully.'
        # initScript()
        # print 'Init task scripts successfully.'
    elif params.get('register'):
        if params.get('model'):
            setDatamodel(os.path.abspath(params.get('<filepath>')))
        elif params.get('unit'):
            setUnit(os.path.abspath(params.get('<filepath>')))
        elif params.get('article'):
            setArticle(os.path.abspath(params.get('<filepath>')))
        else:
            print 'Nothing to do.'
    else:
        print 'Nothing to do.'